# JSON Configuration
json_config: "conf/data.json"

# YAML Configuration
yaml_config: "conf/data.yaml"

biographic_config: "conf/biographic_data.json"

processes:
    - bin: sample_one
      children: sample_one.1 sample_one.2 sample_one.3
      cwd: tests
    - bin: sample_two
      children: []
      cwd: tests
    - bin: sample_three
      children: sample_three.1 sample_three.2 sample_three.3
      cwd: tests
    - bin: sample_four
      children: []
      cwd: tests
    - bin: sample_five
      children: sample_five.1 sample_five.2 sample_five.3
      cwd: tests
